import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Nav from "@/components/Nav/Nav";
import Search from "@/components/Search/Search";
import { categories } from "@/data/Arrays";
import React from "react";

function Articles() {
  return (
    <>
      <Head>
        <title>Articles - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-screen">
        <Search />
        <Nav />
        <header className="flex items-center justify-center w-full pt-32 pb-16 dark:text-white">
          <h1 className="text-9xl allLM:text-8xl allEM:text-6xl allT:text-5xl">
            Articles
          </h1>
        </header>

        <section className="h-full py-10 px-14 allIL:px-5">
          <div className="grid h-full grid-cols-3 allLM:grid-cols-2 allEMT:grid-cols-1 allLM:gap-8 gap-14">
            {categories.map((category) => {
              return (
                <div
                  key={category.id}
                  className="w-full allEMT:max-w-[420px] flex flex-col items-center justify-center duration-500 mx-auto"
                >
                  <div className="relative w-full overflow-hidden aspect-video rounded-xl">
                    <Image
                      src={category.imgsrc}
                      fill
                      priority
                      sizes="(max-width: 768px) 100vw,
                        (max-width: 1200px) 50vw,
                        33vw"
                      alt="Category Image"
                    />
                  </div>

                  <div className="flex items-center w-full gap-4 py-10 duration-500 dark:text-white">
                    <div className="relative w-10 h-10 overflow-hidden rounded-full">
                      <Image
                        src={category.imgsrc}
                        fill
                        priority
                        sizes="(max-width: 768px) 100vw,
                          (max-width: 1200px) 50vw,
                          33vw"
                        alt="Category Image"
                      />
                    </div>
                    <Link href="#" className="duration-300 hover:opacity-50">
                      <h5 className="text-3xl allT:text-2xl">
                        {category.title}
                      </h5>
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </div>
    </>
  );
}

export default Articles;
