import Head from "next/head";

import ArticleCard from "@/components/UI/Cards/ArticleCard";
import Nav from "@/components/UI/Nav/Nav";
import { categories } from "@/static-data/Arrays";

function Articles() {
  return (
    <>
      <Head>
        <title>Articles - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-screen">
        <Nav />
        <section className="w-full pt-20 pb-1 text-center dark:text-white">
          <h1 className="text-6xl xl:text-9xl md:text-8xl xs:text-5xl">
            Articles
          </h1>
        </section>

        <section className="h-full px-5 py-10 xl:px-14">
          <div className="grid h-full grid-cols-1 md:gap-8 xl:grid-cols-3 md:grid-cols-2 gap-14 xl:gap-14">
            {categories.map((category) => (
              <ArticleCard key={category.id} category={category} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}

export default Articles;
