import Head from "next/head";

import CategoryCard from "@/components/UI/Cards/CategoryCard";
import Footer from "@/components/UI/Footer";
import Nav from "@/components/UI/Nav/Nav";
import { categories } from "@/static-data/Arrays";

function Categories() {
  return (
    <>
      <Head>
        <title>Categories - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-screen">
        <Nav />
        <section className="w-full pt-32 pb-16 text-center dark:text-white">
          <h1 className="text-6xl xl:text-9xl md:text-8xl xs:text-5xl">
            Categories
          </h1>
        </section>

        <section className="h-full px-5 pt-10 pb-14 lg:px-14">
          <div className="h-full grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 md:gap-8 gap-14">
            {categories.map((category) => (
              <CategoryCard key={category.id} category={category} />
            ))}
          </div>
        </section>
        <Footer />
      </main>
    </>
  );
}

export default Categories;
