import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { config, dom } from "@fortawesome/fontawesome-svg-core";
import Search from "@/components/Search/Search";
import Nav from "@/components/Nav";
import { categories } from "@/data/Arrays";

config.autoAddCss = false;

function News() {
  return (
    <>
      <Head>
        <title>News - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{dom.css()}</style>
      </Head>
      <div className="w-screen flex flex-col">
        <Search />
        <Nav />
        <header className="w-full dark:text-white pt-32 pb-16 flex items-center justify-center">
          <h1 className="text-9xl allLM:text-8xl allEM:text-6xl allT:text-5xl">
            News
          </h1>
        </header>

        <section className="py-10 px-14 allIL:px-5 h-full">
          <div className="max-w-[1280px] grid grid-cols-4 allLM:grid-cols-2 allEMT:grid-cols-1 allLM:gap-8 gap-14 h-full mx-auto">
            <div className="w-full allIL:h-[300px] border border-black dark:border-white col-span-2 row-span-2 allEMT:col-span-1 rounded-2xl"></div>
            <div className="w-full h-[300px] border border-black dark:border-white col-span-2 allEMT:col-span-1 rounded-2xl"></div>
            <div className="w-full h-[300px] border border-black dark:border-white col-span-2 allEMT:col-span-1 rounded-2xl"></div>
          </div>

          <div className="grid grid-cols-3 allLM:grid-cols-2 allEMT:grid-cols-1 allLM:gap-8 gap-14 h-full mt-20">
            {categories.map((category) => {
              return (
                <div
                  key={category.id}
                  className="w-full allEMT:max-w-[420px] flex flex-col items-center justify-center duration-500 mx-auto"
                >
                  <div className="relative w-full aspect-video rounded-xl overflow-hidden">
                    <Image
                      src={category.imgsrc}
                      fill
                      priority
                      sizes="(max-width: 768px) 100vw,
                        (max-width: 1200px) 50vw,
                        33vw"
                      alt="Category Image"
                    />
                  </div>

                  <div className="w-full dark:text-white flex items-center py-10 duration-500">
                    <Link href="#" className="hover:opacity-50 duration-300">
                      <h5 className="text-3xl allT:text-2xl">
                        {category.title}
                      </h5>
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </div>
    </>
  );
}

export default News;
