import Head from "next/head";

import NewsCard from "@/components/UI/Cards/NewsCard";
import Nav from "@/components/UI/Nav/Nav";
import { categories } from "@/static-data/Arrays";

function News() {
  return (
    <>
      <Head>
        <title>News - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-screen">
        <Nav />
        <section className="w-full pt-32 pb-16 text-center dark:text-white">
          <h1 className="text-6xl xl:text-9xl md:text-8xl xs:text-5xl">News</h1>
        </section>

        <section className="h-full px-5 py-10 xl:px-14">
          <div className="max-w-[1328px] grid xl:grid-cols-4 md:grid-cols-2 grid-cols-1 md:gap-8 gap-14 xl:gap-14 h-full mx-auto">
            <div className="w-full h-[300px] xl:h-auto border border-black dark:border-white md:col-span-2 row-span-2 col-span-1 rounded-2xl"></div>
            <div className="w-full h-[300px] border border-black dark:border-white lg:col-span-2 col-span-1 rounded-2xl"></div>
            <div className="w-full h-[300px] border border-black dark:border-white lg:col-span-2 col-span-1 rounded-2xl"></div>
          </div>

          <div className="h-full mt-20 grid grid-cols-1 md:gap-8 xl:grid-cols-3 md:grid-cols-2 xl:gap-14 gap-14">
            {categories.map((category) => (
              <NewsCard key={category.id} category={category} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}

export default News;
