import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Nav from "@/components/Nav/Nav";
import Search from "@/components/Search/Search";
import { categories } from "@/data/Arrays";
import React from "react";

function News() {
  return (
    <>
      <Head>
        <title>News - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-screen">
        <Search />
        <Nav />
        <header className="flex items-center justify-center w-full pt-32 pb-16 dark:text-white">
          <h1 className="text-9xl allLM:text-8xl allEM:text-6xl allT:text-5xl">
            News
          </h1>
        </header>

        <section className="h-full py-10 px-14 allIL:px-5">
          <div className="max-w-[1280px] grid grid-cols-4 allLM:grid-cols-2 allEMT:grid-cols-1 allLM:gap-8 gap-14 h-full mx-auto">
            <div className="w-full allIL:h-[300px] border border-black dark:border-white col-span-2 row-span-2 allEMT:col-span-1 rounded-2xl"></div>
            <div className="w-full h-[300px] border border-black dark:border-white col-span-2 allEMT:col-span-1 rounded-2xl"></div>
            <div className="w-full h-[300px] border border-black dark:border-white col-span-2 allEMT:col-span-1 rounded-2xl"></div>
          </div>

          <div className="grid h-full grid-cols-3 mt-20 allLM:grid-cols-2 allEMT:grid-cols-1 allLM:gap-8 gap-14">
            {categories.map((category) => {
              return (
                <div
                  key={category.id}
                  className="w-full allEMT:max-w-[420px] flex flex-col items-center justify-center duration-500 mx-auto"
                >
                  <div className="relative w-full overflow-hidden aspect-video rounded-xl">
                    <Image
                      src={category.imgsrc}
                      fill
                      placeholder="blur"
                      alt={category.title}
                    />
                  </div>

                  <div className="flex items-center w-full py-10 duration-500 dark:text-white">
                    <Link href="#" className="duration-300 hover:opacity-50">
                      <h5 className="text-3xl allT:text-2xl">
                        {category.title}
                      </h5>
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </div>
    </>
  );
}

export default News;
