import Head from "next/head";

import ALastSection from "@/components/About-Page-Components/ALastSection";
import ASection1 from "@/components/About-Page-Components/ASection1";
import ASection2 from "@/components/About-Page-Components/ASection2";
import ASection3 from "@/components/About-Page-Components/ASection3";
import ASection4 from "@/components/About-Page-Components/ASection4";
import Footer from "@/components/UI/Footer";
import Nav from "@/components/UI/Nav/Nav";

function About() {
  return (
    <>
      <Head>
        <title>About - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-screen">
        <Nav />
        <section className="w-full pt-32 pb-16 text-center dark:text-white xl:pb-0 md:pb-28">
          <h1 className="text-6xl xl:text-9xl md:text-8xl xs:text-5xl">
            About us
          </h1>
        </section>
        <ASection1 />
        <ASection2 />
        <ASection3 />
        <ALastSection />
        <ASection4 />
        <Footer />
      </main>
    </>
  );
}

export default About;
