import React from "react";
import Head from "next/head";
import { config, dom } from "@fortawesome/fontawesome-svg-core";
import Search from "@/components/Search/Search";
import Nav from "@/components/Nav";
import ASection1 from "@/components/About-Components/ASection1";
import ASection2 from "@/components/About-Components/ASection2";
import ASection3 from "@/components/About-Components/ASection3";
import ASection4 from "@/components/About-Components/ASection4";
import Footer from "@/components/Home-Components/sections/Footer";
import ALastSection from "@/components/About-Components/ALastSection";

config.autoAddCss = false;

function About() {
  return (
    <>
      <Head>
        <title>About - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{dom.css()}</style>
      </Head>
      <div className="w-screen flex flex-col">
        <Search />
        <Nav />
        <header className="w-full dark:text-white pt-32 pb-16 allLM:pb-32 flex items-center justify-center">
          <h1 className="text-9xl allLM:text-8xl allEM:text-6xl allT:text-5xl">
            About us
          </h1>
        </header>
        <ASection1 />
        <ASection2 />
        <ASection3 />
        <ALastSection />
        <ASection4 />
        <Footer />
      </div>
    </>
  );
}

export default About;
