import { useEffect } from "react";
import { config, dom } from "@fortawesome/fontawesome-svg-core";
import useStore from "../providers/navStore";
import Head from "next/head";
import Splash from "./Page-Components/Home-Components/features/Splash-Screen/Splash";
import Search from "./Page-Components/Home-Components/features/Search/Search";
import Nav from "./Page-Components/Home-Components/sections/Nav";
import Hero from "./Page-Components/Home-Components/sections/Hero";
import MainBody from "./Page-Components/Home-Components/sections/MainBody/MainBody";
import Footer from "./Page-Components/Home-Components/sections/Footer";

config.autoAddCss = false;

export default function Home() {
  const { splash, toggleSplash } = useStore();

  useEffect(() => {
    const timeOut = setTimeout(() => {
      toggleSplash();
    }, 2500);
    return () => clearTimeout(timeOut);
  }, [toggleSplash]);

  return (
    <>
      <Head>
        <title>The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{dom.css()}</style>
      </Head>
      <div
        className={`${
          splash ? "h-screen overflow-hidden" : "h-auto overflow-scroll"
        }`}
      >
        <Splash />
        <Search />
        <Nav />
        <Hero />
        <MainBody />
        <Footer />
      </div>
    </>
  );
}
