import Head from "next/head";
import Image from "next/image";

import Bookmarks from "@/components/Profile-Components/Bookmarks";
import EditProfile from "@/components/Profile-Components/EditProfile";
import Nav from "@/components/UI/Nav/Nav";
import { useState } from "react";
import { FaChevronCircleUp } from "react-icons/fa";

import MyLogoImg from "../public/Hero/My Logo 1.jpg";

const lists = [
  {
    id: 1,
    title: "Bookmarks",
    link: "bookmarks",
  },
  {
    id: 2,
    title: "History",
    link: "history",
  },
  {
    id: 3,
    title: "Edit profile",
    link: "editprofile",
  },
];

function About() {
  const [shownList, setShownList] = useState("bookmarks");

  const handleShownList = (list) => {
    setShownList(list);
  };

  return (
    <>
      <Head>
        <title>Profile - The Watchers.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-screen h-[100dvh] flex-col md:flex-row relative">
        <Nav />
        <section className="relative flex flex-col items-start justify-center h-full px-5 pt-20 border-r gap-4 md:px-8 basis-1/4 md:pt-0">
          <div className="relative mx-auto overflow-hidden border rounded-full md:w-56 aspect-square w-36">
            <Image
              src={MyLogoImg}
              fill
              sizes="(max-width: 767px) 100vw, (max-width: 1200px) 50vw, 33vw"
              priority
              placeholder="blur"
              alt="Profile picture"
            />
          </div>

          <div className="w-full text-center space-y-2">
            <h1 className="text-2xl">Mainasara Olulanke</h1>

            <p className="px-2 md:px-0 dark:opacity-70">
              Front-end Engineer by day, Space Enthusiast by night
            </p>
          </div>
        </section>

        <section className="pt-8 overflow-visible md:overflow-scroll grow">
          <div className="sticky z-10 flex w-full gap-4 py-4 bg-white border-b md:justify-evenly justify-between px-5 md:px-0 dark:bg-[#010409] top-16">
            {lists.map((list) => (
              <button
                key={list.id}
                onClick={() => handleShownList(list.link)}
                className={`relative transition-opacity hover:opacity-50 ${
                  shownList === list.link
                    ? "after:content-[''] after:absolute after:left-0 after:-bottom-4 after:h-[3px] after:rounded-full after:w-full after:bg-black dark:after:bg-white"
                    : ""
                } `}
              >
                {list.title}
              </button>
            ))}
          </div>

          <div id="top" className="scroll-mt-[120px]"></div>

          {shownList === "bookmarks" || shownList === "history" ? (
            <Bookmarks />
          ) : (
            <EditProfile />
          )}
        </section>

        <a
          href="#top"
          className="fixed z-10 px-4 py-4 text-xl text-white bg-black border border-black rounded-full duration-300 md:right-8 right-5 md:bottom-8 bottom-5 h-fit w-fit dark:bg-white 2xl:text-2xl dark:text-black dark:hover:bg-black dark:hover:text-white dark:hover:border-white"
        >
          <FaChevronCircleUp />
        </a>
      </main>
    </>
  );
}

export default About;
